# Generated by Django 6.0.2 on 2026-02-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelintent',
            name='adults',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='travelintent',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
