# Generated by Django 6.0.2 on 2026-02-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_travelintent_adults_travelintent_departure_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelintent',
            name='budget',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelintent',
            name='max_stops',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelintent',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
